import { z } from "zod"
import { CRUDPage } from "@/components/crud/CRUDPage"
import { Badge } from "@/components/ui/badge"
import { booleanFromString, optionalString, stringFromAny } from "@/lib/schema-helpers"
import type { FormField, CRUDConfig, BaseEntity } from "@/types"
import type { DataTableColumn } from "@/components/crud/DataTable"

// Tipo basado en Google Sheets (nombres mapeados a inglés)
interface CentroDistribucion extends BaseEntity {
  code?: string
  name: string
  address?: string
  city?: string
  country?: string
  timezone?: string
  phone?: string
  email?: string
  is_active?: boolean | string
}

// Schema de validación (nombres mapeados)
const centroSchema = z.object({
  code: stringFromAny,
  name: z.string().min(2, "El nombre debe tener al menos 2 caracteres"),
  address: optionalString,
  city: optionalString,
  country: optionalString,
  timezone: optionalString,
  phone: stringFromAny,
  email: optionalString,
  is_active: booleanFromString.optional(),
})

// Configuración del CRUD
const config: CRUDConfig = {
  entity: "centros_distribucion",
  labels: {
    singular: "Centro de Distribución",
    plural: "Centros de Distribución",
  },
  displayField: "name",
  permissions: {
    create: true,
    read: true,
    update: true,
    delete: true,
  },
  messages: {
    create: {
      success: "Centro de distribución creado exitosamente",
      error: "Error al crear el centro de distribución",
    },
    update: {
      success: "Centro de distribución actualizado exitosamente",
      error: "Error al actualizar el centro de distribución",
    },
    delete: {
      success: "Centro de distribución eliminado exitosamente",
      error: "Error al eliminar el centro de distribución",
    },
  },
}

// Columnas de la tabla (usando nombres mapeados)
const columns: DataTableColumn<CentroDistribucion>[] = [
  { 
    key: "code" as keyof CentroDistribucion, 
    label: "Código", 
    sortable: true,
    render: (value) => value || '-'
  },
  { 
    key: "name" as keyof CentroDistribucion, 
    label: "Nombre", 
    sortable: true 
  },
  { 
    key: "address" as keyof CentroDistribucion, 
    label: "Dirección",
    render: (value) => value || '-'
  },
  { 
    key: "city" as keyof CentroDistribucion, 
    label: "Ciudad",
    render: (value) => value || '-'
  },
  { 
    key: "country" as keyof CentroDistribucion, 
    label: "País",
    render: (value) => value || '-'
  },
  { 
    key: "timezone" as keyof CentroDistribucion, 
    label: "Zona Horaria",
    render: (value) => value || '-'
  },
  { 
    key: "phone" as keyof CentroDistribucion, 
    label: "Teléfono",
    render: (value) => value || '-'
  },
  {
    key: "is_active" as keyof CentroDistribucion,
    label: "Estado",
    render: (value) => {
      const isActive = value === true || value === 'TRUE' || value === 'true' || value === 'Sí' || value === undefined
      return (
        <Badge variant={isActive ? "success" : "secondary"}>
          {isActive ? "Activo" : "Inactivo"}
        </Badge>
      )
    },
  },
]

// Lista de países de América
const PAISES_AMERICA = [
  { value: "Guatemala", label: "Guatemala" },
  { value: "México", label: "México" },
  { value: "Estados Unidos", label: "Estados Unidos" },
  { value: "Canadá", label: "Canadá" },
  { value: "Argentina", label: "Argentina" },
  { value: "Brasil", label: "Brasil" },
  { value: "Chile", label: "Chile" },
  { value: "Colombia", label: "Colombia" },
  { value: "Costa Rica", label: "Costa Rica" },
  { value: "Cuba", label: "Cuba" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "El Salvador", label: "El Salvador" },
  { value: "Honduras", label: "Honduras" },
  { value: "Nicaragua", label: "Nicaragua" },
  { value: "Panamá", label: "Panamá" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Perú", label: "Perú" },
  { value: "Puerto Rico", label: "Puerto Rico" },
  { value: "República Dominicana", label: "República Dominicana" },
  { value: "Uruguay", label: "Uruguay" },
  { value: "Venezuela", label: "Venezuela" },
  { value: "Belice", label: "Belice" },
  { value: "Bolivia", label: "Bolivia" },
  { value: "Guyana", label: "Guyana" },
  { value: "Surinam", label: "Surinam" },
  { value: "Jamaica", label: "Jamaica" },
  { value: "Haití", label: "Haití" },
  { value: "Trinidad y Tobago", label: "Trinidad y Tobago" },
]

// Ciudades/Departamentos por país
const CIUDADES_POR_PAIS: Record<string, { value: string; label: string }[]> = {
  "Guatemala": [
    { value: "Guatemala", label: "Guatemala" },
    { value: "Alta Verapaz", label: "Alta Verapaz" },
    { value: "Baja Verapaz", label: "Baja Verapaz" },
    { value: "Chimaltenango", label: "Chimaltenango" },
    { value: "Chiquimula", label: "Chiquimula" },
    { value: "El Progreso", label: "El Progreso" },
    { value: "Escuintla", label: "Escuintla" },
    { value: "Huehuetenango", label: "Huehuetenango" },
    { value: "Izabal", label: "Izabal" },
    { value: "Jalapa", label: "Jalapa" },
    { value: "Jutiapa", label: "Jutiapa" },
    { value: "Petén", label: "Petén" },
    { value: "Quetzaltenango", label: "Quetzaltenango" },
    { value: "Quiché", label: "Quiché" },
    { value: "Retalhuleu", label: "Retalhuleu" },
    { value: "Sacatepéquez", label: "Sacatepéquez" },
    { value: "San Marcos", label: "San Marcos" },
    { value: "Santa Rosa", label: "Santa Rosa" },
    { value: "Sololá", label: "Sololá" },
    { value: "Suchitepéquez", label: "Suchitepéquez" },
    { value: "Totonicapán", label: "Totonicapán" },
    { value: "Zacapa", label: "Zacapa" },
  ],
  "México": [
    { value: "Ciudad de México", label: "Ciudad de México" },
    { value: "Aguascalientes", label: "Aguascalientes" },
    { value: "Baja California", label: "Baja California" },
    { value: "Baja California Sur", label: "Baja California Sur" },
    { value: "Campeche", label: "Campeche" },
    { value: "Chiapas", label: "Chiapas" },
    { value: "Chihuahua", label: "Chihuahua" },
    { value: "Coahuila", label: "Coahuila" },
    { value: "Colima", label: "Colima" },
    { value: "Durango", label: "Durango" },
    { value: "Estado de México", label: "Estado de México" },
    { value: "Guanajuato", label: "Guanajuato" },
    { value: "Guerrero", label: "Guerrero" },
    { value: "Hidalgo", label: "Hidalgo" },
    { value: "Jalisco", label: "Jalisco" },
    { value: "Michoacán", label: "Michoacán" },
    { value: "Morelos", label: "Morelos" },
    { value: "Nayarit", label: "Nayarit" },
    { value: "Nuevo León", label: "Nuevo León" },
    { value: "Oaxaca", label: "Oaxaca" },
    { value: "Puebla", label: "Puebla" },
    { value: "Querétaro", label: "Querétaro" },
    { value: "Quintana Roo", label: "Quintana Roo" },
    { value: "San Luis Potosí", label: "San Luis Potosí" },
    { value: "Sinaloa", label: "Sinaloa" },
    { value: "Sonora", label: "Sonora" },
    { value: "Tabasco", label: "Tabasco" },
    { value: "Tamaulipas", label: "Tamaulipas" },
    { value: "Tlaxcala", label: "Tlaxcala" },
    { value: "Veracruz", label: "Veracruz" },
    { value: "Yucatán", label: "Yucatán" },
    { value: "Zacatecas", label: "Zacatecas" },
  ],
  "Estados Unidos": [
    { value: "Alabama", label: "Alabama" },
    { value: "Alaska", label: "Alaska" },
    { value: "Arizona", label: "Arizona" },
    { value: "California", label: "California" },
    { value: "Colorado", label: "Colorado" },
    { value: "Florida", label: "Florida" },
    { value: "Georgia", label: "Georgia" },
    { value: "Illinois", label: "Illinois" },
    { value: "New York", label: "New York" },
    { value: "Texas", label: "Texas" },
    { value: "Washington", label: "Washington" },
  ],
  "El Salvador": [
    { value: "San Salvador", label: "San Salvador" },
    { value: "Ahuachapán", label: "Ahuachapán" },
    { value: "Cabañas", label: "Cabañas" },
    { value: "Chalatenango", label: "Chalatenango" },
    { value: "Cuscatlán", label: "Cuscatlán" },
    { value: "La Libertad", label: "La Libertad" },
    { value: "La Paz", label: "La Paz" },
    { value: "La Unión", label: "La Unión" },
    { value: "Morazán", label: "Morazán" },
    { value: "San Miguel", label: "San Miguel" },
    { value: "San Vicente", label: "San Vicente" },
    { value: "Santa Ana", label: "Santa Ana" },
    { value: "Sonsonate", label: "Sonsonate" },
    { value: "Usulután", label: "Usulután" },
  ],
  "Honduras": [
    { value: "Tegucigalpa", label: "Tegucigalpa (Francisco Morazán)" },
    { value: "Atlántida", label: "Atlántida" },
    { value: "Choluteca", label: "Choluteca" },
    { value: "Colón", label: "Colón" },
    { value: "Comayagua", label: "Comayagua" },
    { value: "Copán", label: "Copán" },
    { value: "Cortés", label: "Cortés" },
    { value: "El Paraíso", label: "El Paraíso" },
    { value: "Gracias a Dios", label: "Gracias a Dios" },
    { value: "Intibucá", label: "Intibucá" },
    { value: "Islas de la Bahía", label: "Islas de la Bahía" },
    { value: "La Paz", label: "La Paz" },
    { value: "Lempira", label: "Lempira" },
    { value: "Ocotepeque", label: "Ocotepeque" },
    { value: "Olancho", label: "Olancho" },
    { value: "Santa Bárbara", label: "Santa Bárbara" },
    { value: "Valle", label: "Valle" },
    { value: "Yoro", label: "Yoro" },
  ],
  "Nicaragua": [
    { value: "Managua", label: "Managua" },
    { value: "Boaco", label: "Boaco" },
    { value: "Carazo", label: "Carazo" },
    { value: "Chinandega", label: "Chinandega" },
    { value: "Chontales", label: "Chontales" },
    { value: "Estelí", label: "Estelí" },
    { value: "Granada", label: "Granada" },
    { value: "Jinotega", label: "Jinotega" },
    { value: "León", label: "León" },
    { value: "Madriz", label: "Madriz" },
    { value: "Masaya", label: "Masaya" },
    { value: "Matagalpa", label: "Matagalpa" },
    { value: "Nueva Segovia", label: "Nueva Segovia" },
    { value: "RACCN", label: "RACCN" },
    { value: "RACCS", label: "RACCS" },
    { value: "Río San Juan", label: "Río San Juan" },
    { value: "Rivas", label: "Rivas" },
  ],
  "Costa Rica": [
    { value: "San José", label: "San José" },
    { value: "Alajuela", label: "Alajuela" },
    { value: "Cartago", label: "Cartago" },
    { value: "Guanacaste", label: "Guanacaste" },
    { value: "Heredia", label: "Heredia" },
    { value: "Limón", label: "Limón" },
    { value: "Puntarenas", label: "Puntarenas" },
  ],
  "Panamá": [
    { value: "Panamá", label: "Panamá" },
    { value: "Bocas del Toro", label: "Bocas del Toro" },
    { value: "Chiriquí", label: "Chiriquí" },
    { value: "Coclé", label: "Coclé" },
    { value: "Colón", label: "Colón" },
    { value: "Darién", label: "Darién" },
    { value: "Herrera", label: "Herrera" },
    { value: "Los Santos", label: "Los Santos" },
    { value: "Panamá Oeste", label: "Panamá Oeste" },
    { value: "Veraguas", label: "Veraguas" },
  ],
  "Colombia": [
    { value: "Bogotá D.C.", label: "Bogotá D.C." },
    { value: "Antioquia", label: "Antioquia" },
    { value: "Atlántico", label: "Atlántico" },
    { value: "Bolívar", label: "Bolívar" },
    { value: "Boyacá", label: "Boyacá" },
    { value: "Caldas", label: "Caldas" },
    { value: "Caquetá", label: "Caquetá" },
    { value: "Cauca", label: "Cauca" },
    { value: "Cesar", label: "Cesar" },
    { value: "Córdoba", label: "Córdoba" },
    { value: "Cundinamarca", label: "Cundinamarca" },
    { value: "Huila", label: "Huila" },
    { value: "Magdalena", label: "Magdalena" },
    { value: "Meta", label: "Meta" },
    { value: "Nariño", label: "Nariño" },
    { value: "Norte de Santander", label: "Norte de Santander" },
    { value: "Quindío", label: "Quindío" },
    { value: "Risaralda", label: "Risaralda" },
    { value: "Santander", label: "Santander" },
    { value: "Sucre", label: "Sucre" },
    { value: "Tolima", label: "Tolima" },
    { value: "Valle del Cauca", label: "Valle del Cauca" },
  ],
  "Perú": [
    { value: "Lima", label: "Lima" },
    { value: "Amazonas", label: "Amazonas" },
    { value: "Áncash", label: "Áncash" },
    { value: "Apurímac", label: "Apurímac" },
    { value: "Arequipa", label: "Arequipa" },
    { value: "Ayacucho", label: "Ayacucho" },
    { value: "Cajamarca", label: "Cajamarca" },
    { value: "Callao", label: "Callao" },
    { value: "Cusco", label: "Cusco" },
    { value: "Huancavelica", label: "Huancavelica" },
    { value: "Huánuco", label: "Huánuco" },
    { value: "Ica", label: "Ica" },
    { value: "Junín", label: "Junín" },
    { value: "La Libertad", label: "La Libertad" },
    { value: "Lambayeque", label: "Lambayeque" },
    { value: "Loreto", label: "Loreto" },
    { value: "Madre de Dios", label: "Madre de Dios" },
    { value: "Moquegua", label: "Moquegua" },
    { value: "Pasco", label: "Pasco" },
    { value: "Piura", label: "Piura" },
    { value: "Puno", label: "Puno" },
    { value: "San Martín", label: "San Martín" },
    { value: "Tacna", label: "Tacna" },
    { value: "Tumbes", label: "Tumbes" },
    { value: "Ucayali", label: "Ucayali" },
  ],
  "Chile": [
    { value: "Santiago", label: "Región Metropolitana de Santiago" },
    { value: "Arica y Parinacota", label: "Arica y Parinacota" },
    { value: "Tarapacá", label: "Tarapacá" },
    { value: "Antofagasta", label: "Antofagasta" },
    { value: "Atacama", label: "Atacama" },
    { value: "Coquimbo", label: "Coquimbo" },
    { value: "Valparaíso", label: "Valparaíso" },
    { value: "O'Higgins", label: "O'Higgins" },
    { value: "Maule", label: "Maule" },
    { value: "Ñuble", label: "Ñuble" },
    { value: "Biobío", label: "Biobío" },
    { value: "La Araucanía", label: "La Araucanía" },
    { value: "Los Ríos", label: "Los Ríos" },
    { value: "Los Lagos", label: "Los Lagos" },
    { value: "Aysén", label: "Aysén" },
    { value: "Magallanes", label: "Magallanes" },
  ],
  "Argentina": [
    { value: "Buenos Aires", label: "Buenos Aires" },
    { value: "CABA", label: "Ciudad Autónoma de Buenos Aires" },
    { value: "Catamarca", label: "Catamarca" },
    { value: "Chaco", label: "Chaco" },
    { value: "Chubut", label: "Chubut" },
    { value: "Córdoba", label: "Córdoba" },
    { value: "Corrientes", label: "Corrientes" },
    { value: "Entre Ríos", label: "Entre Ríos" },
    { value: "Formosa", label: "Formosa" },
    { value: "Jujuy", label: "Jujuy" },
    { value: "La Pampa", label: "La Pampa" },
    { value: "La Rioja", label: "La Rioja" },
    { value: "Mendoza", label: "Mendoza" },
    { value: "Misiones", label: "Misiones" },
    { value: "Neuquén", label: "Neuquén" },
    { value: "Río Negro", label: "Río Negro" },
    { value: "Salta", label: "Salta" },
    { value: "San Juan", label: "San Juan" },
    { value: "San Luis", label: "San Luis" },
    { value: "Santa Cruz", label: "Santa Cruz" },
    { value: "Santa Fe", label: "Santa Fe" },
    { value: "Santiago del Estero", label: "Santiago del Estero" },
    { value: "Tierra del Fuego", label: "Tierra del Fuego" },
    { value: "Tucumán", label: "Tucumán" },
  ],
  "Ecuador": [
    { value: "Quito", label: "Pichincha (Quito)" },
    { value: "Guayaquil", label: "Guayas (Guayaquil)" },
    { value: "Azuay", label: "Azuay" },
    { value: "Bolívar", label: "Bolívar" },
    { value: "Cañar", label: "Cañar" },
    { value: "Carchi", label: "Carchi" },
    { value: "Chimborazo", label: "Chimborazo" },
    { value: "Cotopaxi", label: "Cotopaxi" },
    { value: "El Oro", label: "El Oro" },
    { value: "Esmeraldas", label: "Esmeraldas" },
    { value: "Galápagos", label: "Galápagos" },
    { value: "Imbabura", label: "Imbabura" },
    { value: "Loja", label: "Loja" },
    { value: "Los Ríos", label: "Los Ríos" },
    { value: "Manabí", label: "Manabí" },
    { value: "Morona Santiago", label: "Morona Santiago" },
    { value: "Napo", label: "Napo" },
    { value: "Orellana", label: "Orellana" },
    { value: "Pastaza", label: "Pastaza" },
    { value: "Santa Elena", label: "Santa Elena" },
    { value: "Santo Domingo", label: "Santo Domingo de los Tsáchilas" },
    { value: "Sucumbíos", label: "Sucumbíos" },
    { value: "Tungurahua", label: "Tungurahua" },
    { value: "Zamora Chinchipe", label: "Zamora Chinchipe" },
  ],
  "Venezuela": [
    { value: "Caracas", label: "Distrito Capital (Caracas)" },
    { value: "Amazonas", label: "Amazonas" },
    { value: "Anzoátegui", label: "Anzoátegui" },
    { value: "Apure", label: "Apure" },
    { value: "Aragua", label: "Aragua" },
    { value: "Barinas", label: "Barinas" },
    { value: "Bolívar", label: "Bolívar" },
    { value: "Carabobo", label: "Carabobo" },
    { value: "Cojedes", label: "Cojedes" },
    { value: "Delta Amacuro", label: "Delta Amacuro" },
    { value: "Falcón", label: "Falcón" },
    { value: "Guárico", label: "Guárico" },
    { value: "Lara", label: "Lara" },
    { value: "Mérida", label: "Mérida" },
    { value: "Miranda", label: "Miranda" },
    { value: "Monagas", label: "Monagas" },
    { value: "Nueva Esparta", label: "Nueva Esparta" },
    { value: "Portuguesa", label: "Portuguesa" },
    { value: "Sucre", label: "Sucre" },
    { value: "Táchira", label: "Táchira" },
    { value: "Trujillo", label: "Trujillo" },
    { value: "Vargas", label: "Vargas" },
    { value: "Yaracuy", label: "Yaracuy" },
    { value: "Zulia", label: "Zulia" },
  ],
  "Bolivia": [
    { value: "La Paz", label: "La Paz" },
    { value: "Beni", label: "Beni" },
    { value: "Chuquisaca", label: "Chuquisaca" },
    { value: "Cochabamba", label: "Cochabamba" },
    { value: "Oruro", label: "Oruro" },
    { value: "Pando", label: "Pando" },
    { value: "Potosí", label: "Potosí" },
    { value: "Santa Cruz", label: "Santa Cruz" },
    { value: "Tarija", label: "Tarija" },
  ],
  "Paraguay": [
    { value: "Asunción", label: "Asunción" },
    { value: "Alto Paraguay", label: "Alto Paraguay" },
    { value: "Alto Paraná", label: "Alto Paraná" },
    { value: "Amambay", label: "Amambay" },
    { value: "Boquerón", label: "Boquerón" },
    { value: "Caaguazú", label: "Caaguazú" },
    { value: "Caazapá", label: "Caazapá" },
    { value: "Canindeyú", label: "Canindeyú" },
    { value: "Central", label: "Central" },
    { value: "Concepción", label: "Concepción" },
    { value: "Cordillera", label: "Cordillera" },
    { value: "Guairá", label: "Guairá" },
    { value: "Itapúa", label: "Itapúa" },
    { value: "Misiones", label: "Misiones" },
    { value: "Ñeembucú", label: "Ñeembucú" },
    { value: "Paraguarí", label: "Paraguarí" },
    { value: "Presidente Hayes", label: "Presidente Hayes" },
    { value: "San Pedro", label: "San Pedro" },
  ],
  "Uruguay": [
    { value: "Montevideo", label: "Montevideo" },
    { value: "Artigas", label: "Artigas" },
    { value: "Canelones", label: "Canelones" },
    { value: "Cerro Largo", label: "Cerro Largo" },
    { value: "Colonia", label: "Colonia" },
    { value: "Durazno", label: "Durazno" },
    { value: "Flores", label: "Flores" },
    { value: "Florida", label: "Florida" },
    { value: "Lavalleja", label: "Lavalleja" },
    { value: "Maldonado", label: "Maldonado" },
    { value: "Paysandú", label: "Paysandú" },
    { value: "Río Negro", label: "Río Negro" },
    { value: "Rivera", label: "Rivera" },
    { value: "Rocha", label: "Rocha" },
    { value: "Salto", label: "Salto" },
    { value: "San José", label: "San José" },
    { value: "Soriano", label: "Soriano" },
    { value: "Tacuarembó", label: "Tacuarembó" },
    { value: "Treinta y Tres", label: "Treinta y Tres" },
  ],
  "República Dominicana": [
    { value: "Santo Domingo", label: "Distrito Nacional (Santo Domingo)" },
    { value: "Azua", label: "Azua" },
    { value: "Baoruco", label: "Baoruco" },
    { value: "Barahona", label: "Barahona" },
    { value: "Dajabón", label: "Dajabón" },
    { value: "Duarte", label: "Duarte" },
    { value: "El Seibo", label: "El Seibo" },
    { value: "Elías Piña", label: "Elías Piña" },
    { value: "Espaillat", label: "Espaillat" },
    { value: "Hato Mayor", label: "Hato Mayor" },
    { value: "Hermanas Mirabal", label: "Hermanas Mirabal" },
    { value: "Independencia", label: "Independencia" },
    { value: "La Altagracia", label: "La Altagracia" },
    { value: "La Romana", label: "La Romana" },
    { value: "La Vega", label: "La Vega" },
    { value: "María Trinidad Sánchez", label: "María Trinidad Sánchez" },
    { value: "Monseñor Nouel", label: "Monseñor Nouel" },
    { value: "Monte Cristi", label: "Monte Cristi" },
    { value: "Monte Plata", label: "Monte Plata" },
    { value: "Pedernales", label: "Pedernales" },
    { value: "Peravia", label: "Peravia" },
    { value: "Puerto Plata", label: "Puerto Plata" },
    { value: "Samaná", label: "Samaná" },
    { value: "San Cristóbal", label: "San Cristóbal" },
    { value: "San José de Ocoa", label: "San José de Ocoa" },
    { value: "San Juan", label: "San Juan" },
    { value: "San Pedro de Macorís", label: "San Pedro de Macorís" },
    { value: "Sánchez Ramírez", label: "Sánchez Ramírez" },
    { value: "Santiago", label: "Santiago" },
    { value: "Santiago Rodríguez", label: "Santiago Rodríguez" },
    { value: "Santo Domingo Este", label: "Santo Domingo (Provincia)" },
    { value: "Valverde", label: "Valverde" },
  ],
  "Cuba": [
    { value: "La Habana", label: "La Habana" },
    { value: "Artemisa", label: "Artemisa" },
    { value: "Camagüey", label: "Camagüey" },
    { value: "Ciego de Ávila", label: "Ciego de Ávila" },
    { value: "Cienfuegos", label: "Cienfuegos" },
    { value: "Granma", label: "Granma" },
    { value: "Guantánamo", label: "Guantánamo" },
    { value: "Holguín", label: "Holguín" },
    { value: "Isla de la Juventud", label: "Isla de la Juventud" },
    { value: "Las Tunas", label: "Las Tunas" },
    { value: "Matanzas", label: "Matanzas" },
    { value: "Mayabeque", label: "Mayabeque" },
    { value: "Pinar del Río", label: "Pinar del Río" },
    { value: "Sancti Spíritus", label: "Sancti Spíritus" },
    { value: "Santiago de Cuba", label: "Santiago de Cuba" },
    { value: "Villa Clara", label: "Villa Clara" },
  ],
  "Puerto Rico": [
    { value: "San Juan", label: "San Juan" },
    { value: "Bayamón", label: "Bayamón" },
    { value: "Carolina", label: "Carolina" },
    { value: "Ponce", label: "Ponce" },
    { value: "Caguas", label: "Caguas" },
    { value: "Guaynabo", label: "Guaynabo" },
    { value: "Mayagüez", label: "Mayagüez" },
    { value: "Arecibo", label: "Arecibo" },
  ],
  "Belice": [
    { value: "Belmopan", label: "Cayo (Belmopan)" },
    { value: "Belize City", label: "Belize (Belize City)" },
    { value: "Corozal", label: "Corozal" },
    { value: "Orange Walk", label: "Orange Walk" },
    { value: "Stann Creek", label: "Stann Creek" },
    { value: "Toledo", label: "Toledo" },
  ],
  "Jamaica": [
    { value: "Kingston", label: "Kingston" },
    { value: "Clarendon", label: "Clarendon" },
    { value: "Hanover", label: "Hanover" },
    { value: "Manchester", label: "Manchester" },
    { value: "Portland", label: "Portland" },
    { value: "Saint Andrew", label: "Saint Andrew" },
    { value: "Saint Ann", label: "Saint Ann" },
    { value: "Saint Catherine", label: "Saint Catherine" },
    { value: "Saint Elizabeth", label: "Saint Elizabeth" },
    { value: "Saint James", label: "Saint James" },
    { value: "Saint Mary", label: "Saint Mary" },
    { value: "Saint Thomas", label: "Saint Thomas" },
    { value: "Trelawny", label: "Trelawny" },
    { value: "Westmoreland", label: "Westmoreland" },
  ],
  "Haití": [
    { value: "Puerto Príncipe", label: "Ouest (Puerto Príncipe)" },
    { value: "Artibonite", label: "Artibonite" },
    { value: "Centre", label: "Centre" },
    { value: "Grand'Anse", label: "Grand'Anse" },
    { value: "Nippes", label: "Nippes" },
    { value: "Nord", label: "Nord" },
    { value: "Nord-Est", label: "Nord-Est" },
    { value: "Nord-Ouest", label: "Nord-Ouest" },
    { value: "Sud", label: "Sud" },
    { value: "Sud-Est", label: "Sud-Est" },
  ],
  "Trinidad y Tobago": [
    { value: "Puerto España", label: "Puerto España" },
    { value: "San Fernando", label: "San Fernando" },
    { value: "Chaguanas", label: "Chaguanas" },
    { value: "Arima", label: "Arima" },
    { value: "Point Fortin", label: "Point Fortin" },
  ],
  "Canadá": [
    { value: "Ontario", label: "Ontario" },
    { value: "Quebec", label: "Quebec" },
    { value: "British Columbia", label: "British Columbia" },
    { value: "Alberta", label: "Alberta" },
    { value: "Manitoba", label: "Manitoba" },
    { value: "Saskatchewan", label: "Saskatchewan" },
    { value: "Nova Scotia", label: "Nova Scotia" },
    { value: "New Brunswick", label: "New Brunswick" },
    { value: "Newfoundland and Labrador", label: "Newfoundland and Labrador" },
    { value: "Prince Edward Island", label: "Prince Edward Island" },
  ],
  "Brasil": [
    { value: "São Paulo", label: "São Paulo" },
    { value: "Rio de Janeiro", label: "Rio de Janeiro" },
    { value: "Minas Gerais", label: "Minas Gerais" },
    { value: "Bahia", label: "Bahia" },
    { value: "Paraná", label: "Paraná" },
    { value: "Rio Grande do Sul", label: "Rio Grande do Sul" },
    { value: "Pernambuco", label: "Pernambuco" },
    { value: "Ceará", label: "Ceará" },
    { value: "Pará", label: "Pará" },
    { value: "Maranhão", label: "Maranhão" },
    { value: "Santa Catarina", label: "Santa Catarina" },
    { value: "Goiás", label: "Goiás" },
    { value: "Amazonas", label: "Amazonas" },
    { value: "Distrito Federal", label: "Distrito Federal (Brasília)" },
  ],
}

// Función para obtener ciudades según el país
const getCiudadesPorPais = (pais: string): { value: string; label: string }[] => {
  return CIUDADES_POR_PAIS[pais] || []
}

// Lista de zonas horarias de América
const ZONAS_HORARIAS = [
  { value: "America/Guatemala", label: "Guatemala (UTC-6)" },
  { value: "America/Mexico_City", label: "Ciudad de México (UTC-6)" },
  { value: "America/Cancun", label: "Cancún (UTC-5)" },
  { value: "America/Tijuana", label: "Tijuana (UTC-8)" },
  { value: "America/New_York", label: "Nueva York (UTC-5)" },
  { value: "America/Chicago", label: "Chicago (UTC-6)" },
  { value: "America/Denver", label: "Denver (UTC-7)" },
  { value: "America/Los_Angeles", label: "Los Ángeles (UTC-8)" },
  { value: "America/Toronto", label: "Toronto (UTC-5)" },
  { value: "America/Vancouver", label: "Vancouver (UTC-8)" },
  { value: "America/Bogota", label: "Bogotá (UTC-5)" },
  { value: "America/Lima", label: "Lima (UTC-5)" },
  { value: "America/Santiago", label: "Santiago (UTC-4)" },
  { value: "America/Buenos_Aires", label: "Buenos Aires (UTC-3)" },
  { value: "America/Sao_Paulo", label: "São Paulo (UTC-3)" },
  { value: "America/Caracas", label: "Caracas (UTC-4)" },
  { value: "America/Panama", label: "Panamá (UTC-5)" },
  { value: "America/Costa_Rica", label: "Costa Rica (UTC-6)" },
  { value: "America/El_Salvador", label: "El Salvador (UTC-6)" },
  { value: "America/Tegucigalpa", label: "Tegucigalpa (UTC-6)" },
  { value: "America/Managua", label: "Managua (UTC-6)" },
  { value: "America/Santo_Domingo", label: "Santo Domingo (UTC-4)" },
  { value: "America/Havana", label: "La Habana (UTC-5)" },
  { value: "America/Jamaica", label: "Jamaica (UTC-5)" },
  { value: "America/Port-au-Prince", label: "Puerto Príncipe (UTC-5)" },
  { value: "America/Montevideo", label: "Montevideo (UTC-3)" },
  { value: "America/Asuncion", label: "Asunción (UTC-4)" },
  { value: "America/La_Paz", label: "La Paz (UTC-4)" },
  { value: "America/Guayaquil", label: "Guayaquil (UTC-5)" },
]

// Campos del formulario (usando nombres mapeados)
const formFields: FormField[] = [
  {
    name: "code",
    label: "Código",
    type: "text",
    placeholder: "Código del centro",
  },
  {
    name: "name",
    label: "Nombre",
    type: "text",
    required: true,
    placeholder: "Nombre del centro de distribución",
  },
  {
    name: "address",
    label: "Dirección",
    type: "textarea",
    placeholder: "Dirección completa",
    className: "sm:col-span-2",
  },
  {
    name: "country",
    label: "País",
    type: "select",
    placeholder: "Seleccionar país...",
    options: PAISES_AMERICA,
    defaultValue: "Guatemala",
  },
  {
    name: "city",
    label: "Ciudad / Departamento",
    type: "select",
    placeholder: "Seleccionar ciudad...",
    dependsOn: "country",
    getOptions: getCiudadesPorPais,
  },
  {
    name: "timezone",
    label: "Zona Horaria",
    type: "select",
    placeholder: "Seleccionar zona horaria...",
    options: ZONAS_HORARIAS,
    defaultValue: "America/Guatemala",
  },
  {
    name: "phone",
    label: "Teléfono",
    type: "text",
    placeholder: "Teléfono de contacto",
  },
  {
    name: "email",
    label: "Email",
    type: "email",
    placeholder: "correo@ejemplo.com",
  },
  {
    name: "is_active",
    label: "Activo",
    type: "switch",
    defaultValue: true,
  },
]

export function CentrosDistribucionPage() {
  return (
    <CRUDPage<CentroDistribucion>
      config={config}
      entityName="centros_distribucion"
      columns={columns}
      formFields={formFields}
      formSchema={centroSchema}
      searchFields={["code", "name", "city", "country"] as (keyof CentroDistribucion)[]}
      defaultValues={{ 
        is_active: true,
        country: "Guatemala",
        city: "Guatemala",
        timezone: "America/Guatemala",
      }}
    />
  )
}
